import '@angular/compiler';
import { Component, type Type } from '@angular/core';
import { TestBed } from '@angular/core/testing';
import { describe, expect, it } from 'vitest';
import { createDashboardStore, type Cell, type DataModel, type Row } from '@sentropic/dataviz-core';
import { AreaRangeChart } from '../../dist/lib/AreaRangeChart.js';
import { AreaSplineRangeChart } from '../../dist/lib/AreaSplineRangeChart.js';
import { CandlestickChart } from '../../dist/lib/CandlestickChart.js';
import { ChoroplethMap } from '../../dist/lib/ChoroplethMap.js';
import { ColumnRangeChart } from '../../dist/lib/ColumnRangeChart.js';
import { DumbbellChart } from '../../dist/lib/DumbbellChart.js';
import { GeoClusterMap } from '../../dist/lib/GeoClusterMap.js';
import { GeoDensityMap } from '../../dist/lib/GeoDensityMap.js';
import { GeoFlowMap } from '../../dist/lib/GeoFlowMap.js';
import { GeoHexbinMap } from '../../dist/lib/GeoHexbinMap.js';
import { GeoJsonMap } from '../../dist/lib/GeoJsonMap.js';
import { GeoPointMap } from '../../dist/lib/GeoPointMap.js';
import { HLCChart } from '../../dist/lib/HLCChart.js';
import { HeikinAshiChart } from '../../dist/lib/HeikinAshiChart.js';
import { HollowCandlestickChart } from '../../dist/lib/HollowCandlestickChart.js';
import { OHLCChart } from '../../dist/lib/OHLCChart.js';
import { PackedBubbleChart } from '../../dist/lib/PackedBubbleChart.js';
import { RenkoChart } from '../../dist/lib/RenkoChart.js';
import { RoseChart } from '../../dist/lib/RoseChart.js';
import { SunburstChart } from '../../dist/lib/SunburstChart.js';

/**
 * One table for the twenty adapters generated by tools/dataviz-angular-port.
 * They differ only in which builder feeds which design-system component, so the
 * assertions are the same for all of them and the expectations are data:
 *
 *  - the design-system component really rendered (its `data-st-component` marker);
 *  - the caller's `class` reaches the DS root, next to the adapter's own class;
 *  - the accessible value list carries the shared `Data values for <label>` label
 *    and exactly the values the adapter derived;
 *  - a selection made in ANOTHER cross-filter view changes what is rendered,
 *    which is what proves the store subscription and the memoised recompute are
 *    wired (a broken subscription leaves the first render in place).
 */

// `buildGeoJsonLayerModel` reads a geometry OBJECT from the cell, not a JSON string.
const geo = (lon: number, lat: number) =>
  ({
    type: 'Polygon',
    coordinates: [[[lon, lat], [lon + 1, lat], [lon + 1, lat + 1], [lon, lat]]],
  }) as unknown as Cell;

const DAY = 86_400_000;
const T0 = Date.UTC(2026, 0, 1);

const model: DataModel = {
  dimensions: [
    { id: 'service', label: 'Service', type: 'discrete' },
    { id: 'region', label: 'Region', type: 'discrete' },
    { id: 'shape', label: 'Shape', type: 'discrete' },
    { id: 'ts', label: 'Timestamp', type: 'continuous' },
    { id: 'lat', label: 'Latitude', type: 'continuous' },
    { id: 'lon', label: 'Longitude', type: 'continuous' },
    { id: 'dstLat', label: 'Target latitude', type: 'continuous' },
    { id: 'dstLon', label: 'Target longitude', type: 'continuous' },
  ],
  measures: [
    { id: 'amount', label: 'Amount', aggregation: 'sum' },
    { id: 'open', label: 'Open', aggregation: 'avg' },
    { id: 'high', label: 'High', aggregation: 'max' },
    { id: 'low', label: 'Low', aggregation: 'min' },
    { id: 'close', label: 'Close', aggregation: 'avg' },
  ],
};

const rows: Row[] = [
  { service: 'checkout', region: 'eu', shape: geo(2, 48), ts: T0, lat: 48.85, lon: 2.35, dstLat: 51.5, dstLon: -0.12, amount: 10, open: 100, high: 110, low: 95, close: 105 },
  { service: 'checkout', region: 'us', shape: geo(-74, 40), ts: T0 + DAY, lat: 40.71, lon: -74.0, dstLat: 34.05, dstLon: -118.24, amount: 5, open: 105, high: 112, low: 101, close: 102 },
  { service: 'billing', region: 'eu', shape: geo(13, 52), ts: T0 + 2 * DAY, lat: 52.52, lon: 13.4, dstLat: 41.9, dstLon: 12.5, amount: 7, open: 102, high: 108, low: 99, close: 107 },
];

type Items = string[] | { count: number; first: string; last: string };

type Case = {
  family: string;
  name: string;
  component: Type<unknown>;
  ds: string;
  ownClass?: string;
  template: string;
  items: Items;
  after: Items;
  mark?: [string, number, number];
};

const cases: Case[] = [
  {
    family: "geo maps on the DS GeoChart",
    name: "ChoroplethMap",
    component: ChoroplethMap,
    ds: "GeoChart",
    ownClass: "st-choroplethMap",
    template: `<st-dataviz-choropleth-map [store]="store" viewId="v" region="region" measure="amount" geometry="shape" label="L" class="probe"></st-dataviz-choropleth-map>`,
    items: ["L: 2 régions", "eu: 17", "us: 5"],
    after: ["L: 1 régions", "eu: 7"],
    mark: [".st-geoMap__region", 2, 1],
  },
  {
    family: "geo maps on the DS GeoChart",
    name: "GeoClusterMap",
    component: GeoClusterMap,
    ds: "GeoChart",
    ownClass: "st-geoClusterMap",
    template: `<st-dataviz-geo-cluster-map [store]="store" viewId="v" latitude="lat" longitude="lon" label="L" class="probe"></st-dataviz-geo-cluster-map>`,
    items: ["L: 3", "cluster:0: 1", "cluster:1: 1", "cluster:2: 1"],
    after: ["L: 1", "cluster:0: 1"],
    mark: [".st-geoMap__cluster", 3, 1],
  },
  {
    family: "geo maps on the DS GeoChart",
    name: "GeoDensityMap",
    component: GeoDensityMap,
    ds: "GeoChart",
    ownClass: "st-geoDensityMap",
    template: `<st-dataviz-geo-density-map [store]="store" viewId="v" latitude="lat" longitude="lon" label="L" class="probe"></st-dataviz-geo-density-map>`,
    items: ["L: 3 points", "(48.85, 2.35): 1", "(40.71, -74): 1", "(52.52, 13.4): 1"],
    after: ["L: 1 points", "(52.52, 13.4): 1"],
    mark: [".st-geoMap__density", 3, 1],
  },
  {
    family: "geo maps on the DS GeoChart",
    name: "GeoFlowMap",
    component: GeoFlowMap,
    ds: "GeoChart",
    ownClass: "st-geoFlowMap",
    template: `<st-dataviz-geo-flow-map [store]="store" viewId="v" sourceLatitude="lat" sourceLongitude="lon" targetLatitude="dstLat" targetLongitude="dstLon" label="L" class="probe"></st-dataviz-geo-flow-map>`,
    items: ["L: 3", "1 flows: 1", "1 flows: 1", "1 flows: 1"],
    after: ["L: 1", "1 flows: 1"],
    mark: [".st-geoMap__flow", 3, 1],
  },
  {
    family: "geo maps on the DS GeoChart",
    name: "GeoHexbinMap",
    component: GeoHexbinMap,
    ds: "GeoChart",
    ownClass: "st-geoHexbinMap",
    template: `<st-dataviz-geo-hexbin-map [store]="store" viewId="v" latitude="lat" longitude="lon" label="L" class="probe"></st-dataviz-geo-hexbin-map>`,
    items: ["L: 3 alvéoles", "2:56: 1", "-74:47: 1", "13:60: 1"],
    after: ["L: 1 alvéoles", "13:60: 1"],
    mark: [".st-geoMap__hexbin", 3, 1],
  },
  {
    family: "geo maps on the DS GeoChart",
    name: "GeoJsonMap",
    component: GeoJsonMap,
    ds: "GeoChart",
    ownClass: "st-geoJsonMap",
    template: `<st-dataviz-geo-json-map [store]="store" viewId="v" geometry="shape" label="L" class="probe"></st-dataviz-geo-json-map>`,
    items: ["L: 3 entités", "0", "1", "2"],
    after: ["L: 1 entités", "0"],
    mark: [".st-geoMap__feature", 3, 1],
  },
  {
    family: "geo maps on the DS GeoChart",
    name: "GeoPointMap",
    component: GeoPointMap,
    ds: "GeoChart",
    ownClass: "st-geoPointMap",
    template: `<st-dataviz-geo-point-map [store]="store" viewId="v" latitude="lat" longitude="lon" label="L" class="probe"></st-dataviz-geo-point-map>`,
    items: ["L: 3", "0", "1", "2"],
    after: ["L: 1", "0"],
    mark: [".st-geoMap__point", 3, 1],
  },
  {
    family: "OHLC-family charts",
    name: "CandlestickChart",
    component: CandlestickChart,
    ds: "CandlestickChart",
    template: `<st-dataviz-candlestick-chart [store]="store" viewId="v" label_field="region" open="open" high="high" low="low" close="close" label="L" class="probe"></st-dataviz-candlestick-chart>`,
    items: ["eu: O 100 H 110 L 95 C 105", "us: O 105 H 112 L 101 C 102", "eu: O 102 H 108 L 99 C 107"],
    after: ["eu: O 102 H 108 L 99 C 107"],
  },
  {
    family: "OHLC-family charts",
    name: "HeikinAshiChart",
    component: HeikinAshiChart,
    ds: "HeikinAshiChart",
    template: `<st-dataviz-heikin-ashi-chart [store]="store" viewId="v" label_field="region" open="open" high="high" low="low" close="close" label="L" class="probe"></st-dataviz-heikin-ashi-chart>`,
    items: ["eu: O 102.50 H 110 L 95 C 102.50", "us: O 102.50 H 112 L 101 C 105", "eu: O 103.75 H 108 L 99 C 104"],
    after: ["eu: O 104.50 H 108 L 99 C 104"],
  },
  {
    family: "OHLC-family charts",
    name: "HollowCandlestickChart",
    component: HollowCandlestickChart,
    ds: "HollowCandlestickChart",
    template: `<st-dataviz-hollow-candlestick-chart [store]="store" viewId="v" label_field="region" open="open" high="high" low="low" close="close" label="L" class="probe"></st-dataviz-hollow-candlestick-chart>`,
    items: ["eu: O 100 H 110 L 95 C 105", "us: O 105 H 112 L 101 C 102", "eu: O 102 H 108 L 99 C 107"],
    after: ["eu: O 102 H 108 L 99 C 107"],
  },
  {
    family: "OHLC-family charts",
    name: "OHLCChart",
    component: OHLCChart,
    ds: "OHLCChart",
    template: `<st-dataviz-ohlc-chart [store]="store" viewId="v" label_field="region" open="open" high="high" low="low" close="close" label="L" class="probe"></st-dataviz-ohlc-chart>`,
    items: ["eu: O 100 H 110 L 95 C 105", "us: O 105 H 112 L 101 C 102", "eu: O 102 H 108 L 99 C 107"],
    after: ["eu: O 102 H 108 L 99 C 107"],
  },
  {
    family: "OHLC-family charts",
    name: "HLCChart",
    component: HLCChart,
    ds: "HLCChart",
    template: `<st-dataviz-hlc-chart [store]="store" viewId="v" label_field="region" high="high" low="low" close="close" label="L" class="probe"></st-dataviz-hlc-chart>`,
    items: ["eu: H 110 L 95 C 105", "us: H 112 L 101 C 102", "eu: H 108 L 99 C 107"],
    after: ["eu: H 108 L 99 C 107"],
  },
  {
    family: "OHLC-family charts",
    name: "RenkoChart",
    component: RenkoChart,
    ds: "RenkoChart",
    template: `<st-dataviz-renko-chart [store]="store" viewId="v" date="ts" close="close" label="L" class="probe"></st-dataviz-renko-chart>`,
    items: { count: 31, first: '▼ 104.8 → 105', last: '▲ 106.8 → 107' },
    after: [],
  },
  {
    family: "range charts",
    name: "AreaRangeChart",
    component: AreaRangeChart,
    ds: "AreaRangeChart",
    template: `<st-dataviz-area-range-chart [store]="store" viewId="v" x_field="region" low="low" high="high" label="L" class="probe"></st-dataviz-area-range-chart>`,
    items: ["eu: 95 – 110", "us: 101 – 112", "eu: 99 – 108"],
    after: ["eu: 99 – 108"],
  },
  {
    family: "range charts",
    name: "AreaSplineRangeChart",
    component: AreaSplineRangeChart,
    ds: "AreaSplineRangeChart",
    template: `<st-dataviz-area-spline-range-chart [store]="store" viewId="v" x_field="region" low="low" high="high" label="L" class="probe"></st-dataviz-area-spline-range-chart>`,
    items: ["eu: 95 – 110", "us: 101 – 112", "eu: 99 – 108"],
    after: ["eu: 99 – 108"],
  },
  {
    family: "range charts",
    name: "ColumnRangeChart",
    component: ColumnRangeChart,
    ds: "ColumnRangeChart",
    template: `<st-dataviz-column-range-chart [store]="store" viewId="v" category="region" low="low" high="high" label="L" class="probe"></st-dataviz-column-range-chart>`,
    items: ["eu: 95 – 110", "us: 101 – 112", "eu: 99 – 108"],
    after: ["eu: 99 – 108"],
  },
  {
    family: "range charts",
    name: "DumbbellChart",
    component: DumbbellChart,
    ds: "DumbbellChart",
    template: `<st-dataviz-dumbbell-chart [store]="store" viewId="v" category="region" low="low" high="high" label="L" class="probe"></st-dataviz-dumbbell-chart>`,
    items: ["eu: 95 – 110", "us: 101 – 112", "eu: 99 – 108"],
    after: ["eu: 99 – 108"],
  },
  {
    family: "part-of-whole charts",
    name: "RoseChart",
    component: RoseChart,
    ds: "RoseChart",
    template: `<st-dataviz-rose-chart [store]="store" viewId="v" category="region" measure="amount" label="L" class="probe"></st-dataviz-rose-chart>`,
    items: ["eu: 17", "us: 5"],
    after: ["eu: 7"],
    mark: [".st-roseChart__sector", 2, 1],
  },
  {
    family: "part-of-whole charts",
    name: "SunburstChart",
    component: SunburstChart,
    ds: "SunburstChart",
    template: `<st-dataviz-sunburst-chart [store]="store" viewId="v" [hierarchy]="hierarchy" measure="amount" label="L" class="probe"></st-dataviz-sunburst-chart>`,
    items: ["Total, eu, checkout: 10", "Total, eu, billing: 7", "Total, us, checkout: 5"],
    after: ["Total, eu, billing: 7"],
    mark: [".st-sunburstChart__arc", 5, 2],
  },
  {
    family: "part-of-whole charts",
    name: "PackedBubbleChart",
    component: PackedBubbleChart,
    ds: "PackedBubblesChart",
    template: `<st-dataviz-packed-bubble-chart [store]="store" viewId="v" category="region" measure="amount" label="L" class="probe"></st-dataviz-packed-bubble-chart>`,
    items: ["eu: 17", "us: 5"],
    after: ["eu: 7"],
    mark: [".st-packedBubblesChart__bubble", 2, 1],
  },
];

function dataList(root: Element): string[] {
  return Array.from(root.querySelectorAll('ul.st-chartDataList > li')).map((li) => li.textContent?.trim() ?? '');
}

function expectItems(actual: string[], expected: Items, what: string): void {
  if (Array.isArray(expected)) {
    expect(actual, what).toEqual(expected);
    return;
  }
  expect(actual.length, what + ' count').toBe(expected.count);
  expect(actual[0], what + ' first').toBe(expected.first);
  expect(actual[actual.length - 1], what + ' last').toBe(expected.last);
}

for (const [family] of new Map(cases.map((c) => [c.family, true]))) {
  describe(family + ' (angular, generated)', () => {
    for (const testCase of cases.filter((c) => c.family === family)) {
      it(testCase.name + ' renders its DS component from the cross-filtered rows', () => {
        class Host {
          readonly store = createDashboardStore({
            model,
            data: rows,
            crossfilter: { views: { v: { field: 'service' }, other: { field: 'service' } } },
          });
          readonly hierarchy = ['region', 'service'];
        }
        Component({ standalone: true, imports: [testCase.component], template: testCase.template })(Host);

        const fixture = TestBed.createComponent(Host);
        fixture.detectChanges();
        const root = fixture.nativeElement as HTMLElement;

        const marker = root.querySelector('[data-st-component]');
        expect(marker?.getAttribute('data-st-component'), 'DS component').toBe(testCase.ds);
        const classes = marker?.getAttribute('class')?.split(' ') ?? [];
        expect(classes, 'class passthrough').toContain('probe');
        if (testCase.ownClass) expect(classes, 'adapter class').toContain(testCase.ownClass);

        expect(root.querySelector('ul.st-chartDataList')?.getAttribute('aria-label')).toBe('Data values for L');
        expectItems(dataList(root), testCase.items, testCase.name + ' values');
        if (testCase.mark) {
          expect(root.querySelectorAll(testCase.mark[0]).length, testCase.mark[0]).toBe(testCase.mark[1]);
        }

        // A selection in the other view narrows this one: same assertions, new data.
        fixture.componentInstance.store.toggleSelection('other', 'billing');
        fixture.detectChanges();

        expectItems(dataList(root), testCase.after, testCase.name + ' values after narrowing');
        if (testCase.mark) {
          expect(root.querySelectorAll(testCase.mark[0]).length, testCase.mark[0] + ' after').toBe(testCase.mark[2]);
        }
      });
    }
  });
}
