"""Curated design decisions. Names describe responsibilities; no runtime dependency added."""
FW=['svelte','react','vue','angular']
P={}
def pkg(short,layer,scope,why,deps=(),subpaths=(),reuse='',proof='',existing=False,env='TypeScript agnostique, import sans DOM',third=()):
 name='@sentropic/'+short
 P[name]={'name':name,'layer':layer,'scope':scope,'name_rationale':why,'dependencies':['@sentropic/'+d for d in deps],'subpaths':list(subpaths),'reuse':reuse,'acceptance':proof,'existing_name':existing,'environment':env,'third_party_dependencies':list(third),'version_policy':'SemVer indépendant ; tag '+short+'@<version> ; matrice de compatibilité D6 ; aucun tag v* global','dist_tag':'next tant que qualification incomplète, latest après gates propres au package'}
pkg('graph-model','contrats & noyau','Document sémantique typé, entités et relations de première classe, vues, occurrences, références, révisions ; projections de calcul ; AST/CST et provenance par références ; commandes/transactions et validation commune humain-agent ; ports persistence/ressources/présence.','model désigne les identités et invariants sémantiques ; ni géométrie ni widgets.',subpaths=['document','views','references','commands','projection','source','ports'],reuse='Contrats graph/types.ts et dataviz/model.ts comme entrées de compatibilité ; ne pas assimiler Row ou HighLevelGraphInput au nouveau Document.',proof='Références pendantes, relation→relation, occurrences multiples, validation profil, transactions et migrations testées sans DOM.')
pkg('graph-profiles','domaines','Profils versionnés BPMN, ArchiMate, UML/SysML, ER, processus, circuits et contraintes métier ; palettes et règles sémantiques déclaratives.','profiles applique D1 : extensions typées et versions de schéma indépendantes du SemVer du package.',deps=['graph-model'],subpaths=['bpmn','archimate','uml','sysml','entity-relationship','process','circuit'],reuse='Types/relations graphify génériques réutilisables, producteurs de connaissance laissés au produit.',proof='Fixtures positives/négatives par version de profil ; migrations ; couverture métier distincte des glyphes.')
pkg('graph-scene','scène & géométrie','Scène commune, routes et labels calculés, ports, glyphes, buffers, caméra, transformations, spatial index/picking, métriques et transitions géométriques.','scene représente la géométrie prête à peindre, distincte du modèle sémantique.',deps=['graph-model'],subpaths=['scene','geometry','camera','picking','buffers','text','animation'],reuse='graph/{buffers,positions,styles,shape-geometry,render-geometry,edge-geometry,mat4,gitflow-labels}.ts ; helpers DS.',proof='Même identité et géométrie pour SVG/WebGL/DOM/Canvas2D ; picking indépendant backend, tolérances chiffrées ; métriques injectables.')
pkg('graph-codecs','domaines & codecs','Parse/serialize modèles et sources : JSON document, Mermaid, PlantUML/UML, BPMN XML+DI, ArchiMate Exchange, draw.io/mxGraph, Sparx EA XMI par dialecte, Visio VSDX, DOT/xdot, GraphML, Obsidian Canvas, Cypher/GoogleSQL et XML/ZIP sans réseau implicite. Rapports de conversion et conservation AST/CST/extensions.','codecs nomme les conversions bidirectionnelles qualifiées ; exporter une image appartient à graph-export.',deps=['graph-model','graph-profiles','graph-scene'],subpaths=['json','mermaid','plantuml','bpmn','archimate','drawio','xmi','visio','dot','graphml','obsidian','database-scripts','xml','source-map'],reuse='Sérialisations Sentropic existantes comme fixtures/compat ; aucune lib de parser tierce implicitement transportée.',proof='Sous-ensembles documentés par dialecte/version, pertes localisées ; cycle parse/serialize et fixtures hostiles ; aucun round-trip universel promis.')
pkg('graph-processing','processing','Parcours, composantes, tri topologique, chemins (Dijkstra), sous-graphes, agrégation et projections de graphe ; diagnostics structurels pour les layouts.','processing traite la topologie et les données, sans promettre des coordonnées ; sépare les chemins analytiques du routage visuel.',deps=['graph-model'],subpaths=['traversal','components','paths','projection','constraints'],reuse='Extraire uniquement helpers génériques Sentropic ; graphology/Louvain de retrieval restent dans graphify.',proof='Résultats topologiques et cas cycles/multigraphes vérifiés ; provenance conservée ; 0 dependency de renderer.')
pkg('graph-routing','processing / routage','Chemins visuels orthogonaux, octilinéaires, segments, courbes, évitement obstacles, ports/ancres, buses, hyperarêtes, link-to-link, self-loops, labels.','routing distingue les trajectoires dessinées des chemins analytiques et du placement de nœuds.',deps=['graph-model','graph-scene'],subpaths=['orthogonal','octilinear','curves','obstacles','ports','labels','bundles'],reuse='graph/{render-geometry,edge-geometry}.ts, DS arêtes SVG ; comparaison libavoid/Graphviz sans dépendance.',proof='Obstacles, clearance, extrémités, ports, labels et impossibles diagnostiqués ; géométrie commune aux backends.')
pkg('graph-layout','processing / placement','Registre et phases de placement, les 21 références ELK et 10 entrées Graphviz, leurs groupes/options, layouts graphify et DS ; layered, arbres, radial/circulaire, force/stress, grilles, packing/compaction/overlap ; seed/incrémental/contraintes.','layout a un contrat géométrique unique ; familles et variantes en sous-chemins, aucun package par algorithme fournisseur.',deps=['graph-model','graph-processing','graph-scene','graph-routing'],subpaths=['registry','layered','tree','radial','force','stress','grid','packing','compaction','fixed','random','domain'],reuse='graph/layout*.ts ; graphify/src/{graph-layout,hierarchy-layout}.ts ; simulations DS ForceGraph et layouts charts.',proof='Chaque ID/options reference possède fixture et statut ; résultat positions/rects/ports/routes/labels/diagnostics ; déterminisme ≠ stabilité incrémentale ; compat PositionFrame explicite.')
pkg('graph-worker','moteurs / exécution','Protocole de jobs sur snapshots révisionnés, transfert buffers, progrès, annulation, timeout, choix de moteur, rejet résultats périmés et fallback synchrone.','worker nomme le mode d’exécution ; ne présente pas le transport comme un nouvel algorithme.',deps=['graph-model','graph-scene','graph-layout'],subpaths=['protocol','browser','synchronous'],reuse='graphify/studio/src/lib/{layoutWorker,forceLayoutClient}.js ; supprimer alias Vite privé après bascule.',proof='Révision document+vue+projection, jobId/generation ; après édition, ancien résultat refusé ; byte-equivalence sync/worker ; aucun global Worker à import.')
pkg('graph-compiler','compilation','Compilateur unique document/profil/vue → projection, plan de processing et scène/contrats interaction ; métriques texte/image et moteurs injectables ; sortie sérialisable identique pour les quatre frameworks.','compiler décrit la transformation partagée ; views appartient déjà au modèle. D3 ne signifie ni quatre compilateurs, ni un parseur commun à tous dialectes.',deps=['graph-model','graph-profiles','graph-processing','graph-layout','graph-scene'],subpaths=['compile','projection','diagnostics'],reuse='Séparer le raccord générique des scene-layout/studio-render-buffers/graphRendererPayload ; producteur graph.json reste produit.',proof='Un corpus et un hash de scène partagé 4-fw ; aucune API DOM/framework ; diagnostics source→entity→occurrence ; aucune dépendance focus-render/Track.')
pkg('graph','moteurs / compatibilité publique','Renderer Sentropic WebGL2 et Canvas2D ; buffers et API historiques préservés, façade délégante vers scene/layout après extraction compatible.','Nom publié @sentropic/graph préservé ; aucune nouvelle marque remplaçant la bibliothèque.',deps=['graph-scene','graph-layout'],subpaths=['.'],reuse='Intégralité packages/graph (211 exports), tests, golden, bench, licence et provenance ; M1 intact avant extraction.',proof='ESM+CJS+types et 211 exports conservés ; goldens Canvas2D/WebGL ; canari WebGL et fallback restent visibles.',existing=True,env='Backend navigateur WebGL2/Canvas2D ; helpers purs ; import sans instanciation browser à qualifier')
pkg('graph-svg','moteurs de rendu','Peinture SVG de la scène, sérialisation vectorielle, DOM SVG interactif, marqueurs, texte, clip/mask/gradients, images ; support SSR sérialisé.','svg désigne le backend, pas une variante du document ou un codec métier.',deps=['graph-scene'],subpaths=['serialize','dom'],reuse='shapeSvgPath et render-geometry graph ; primitives SVG DS, adaptation sans recopier les composants.',proof='Parité géométrique avec graph ; styles/tokens résolus, font metrics identiques, lien occurrence→element et snapshot SVG.')
pkg('graph-dom','moteurs de rendu','Nœuds HTML-DOM, formulaires, texte/IME, measurements ; composition hybride avec layer arêtes SVG ou WebGL fourni par port, coords/caméra/focus synchronisés.','dom dit explicitement que le backend travaille sur éléments HTML ; HTML ne fournit pas implicitement le routage des arêtes.',deps=['graph-scene'],subpaths=['nodes','measure','hybrid'],reuse='Contrôles DS existants et GraphCanvas Svelte ; rendu HTML générique nouveau à qualifier.',proof='resize/zoom/scroll, arêtes cross-layer, IME/focus/clavier et SSR placeholder, CSP qualifiée ; aucun framework intégré.',env='DOM navigateur ; contrat importable sans document')
pkg('graph-canvas','interaction & canvas','Contrôleur headless sélection, déplacements/redim/rotation, ports/liens, snap/guides/groupes, clipboard, undo-redo, annotations/cerclage, viewport, outils, modes ; commandes validées et ports de persistence/présence.','canvas signifie surface de travail éditable multi-backend ; ne force ni Canvas2D ni état BI.',deps=['graph-model','graph-scene','graph-processing','graph-routing'],subpaths=['controller','commands','tools','clipboard','history','annotations','viewport'],reuse='Gestes GraphCanvas, sélection renderer à extraire vers scene, DiagramAnnotator (ellipse/rect/PNG) ; UI générique via DS.',proof='preview/transaction/persistence distincts ; humains/agents mêmes validations ; undo atomique et conflicts révision ; aucun verrou déduit h2a/Track.')
pkg('graph-export','artefacts / exports','Plan d’export scène, ressources/fonts, SVG/raster/PDF/PPTX/HTML/print, sorties Graphviz et surfaces terminal/native explicitement typées ; page/tile/scale et rapport de fidélité. JSON document délégué au codec ; données CSV à dataviz-core.','export nomme les artefacts livrables distincts de la conversion sémantique ; sous-chemins évitent un package par extension.',deps=['graph-model','graph-scene','graph-svg','graph-codecs'],subpaths=['plan','svg','raster','pdf','pptx','html','print','graphviz','terminal','native-surfaces'],reuse='dataviz-*/lib/chart-export.ts et DiagramAnnotator.toPNG ; maintenir les façades historiques.',proof='SVG/PNG/PDF/print régressions ; PPTX slides/médias/éditabilité explicites ; aucune sortie silencieusement substituée ; pixels vs objets vs sémantique tracés.',env='Plan pur ; /raster,/print browser ; encodeurs isolés/lazy',third=['jspdf ^4.2.1 et svg2pdf.js ^2.7.0 : continuité des imports PDF dataviz existants ; isoler sous /pdf, ne pas importer depuis la racine. Versions finales pins D6 à qualifier. Aucune autre dependency nouvelle autorisée.'])
pkg('graph-recipes','applications réutilisables','186 recettes nommées par slug officiel JointJS, plus composition applications Sentropic ; documents/profils/configuration/commandes et scénarios de démonstration. Hosts docs 4-fw privés pour rendre chaque recette via API publiques.','recipes regroupe des compositions démontrables ; pas 186 packages ni un autre moteur UI.',deps=['graph-model','graph-profiles'],subpaths=['catalog','workflow','modeling','hierarchy','planning','simulation','interaction','rendering','integration','export'],reuse='Graphify studio et demos dataviz/DS comme sources de scénarios ; toute intégration vendor remplacée par port documenté.',proof='Chaque recette dispose de needs/features/capability refs et scénario rendu dans chacun des 4 hosts ; présence dans catalogue ≠ application implémentée.')
for fw in FW:
 pkg('graph-'+fw,'adaptateurs DS','Binding '+fw+' de graph-compiler/canvas et backends : GraphCanvas, palette, inspector, toolbar, minimap, formulaires HTML, contexte et a11y ; consumes controlled DS primitives.','Suffixe '+fw+' nomme le framework ; modèle cohérent avec dataviz-* ; aucune logique de compilation dupliquée.',deps=['graph-model','graph-scene','graph-compiler','graph-canvas','graph-svg','graph-dom','design-system-'+fw,'design-system-themes'],subpaths=['canvas','tools','renderers'],reuse='Svelte GraphCanvas et DiagramAnnotator comme comportement de référence ; React/Vue/Angular adaptés aux conventions DS.',proof='Même contrat et mêmes scènes/commandes, fixtures SSR/clavier/focus/IME/tokens/CSP par framework ; backend graph WebGL fourni explicitement au host.',env='Adapter '+fw+' ; framework peer, SSR qualifié',third=['Peer '+fw+' selon matrice compatible ; aucun JointJS/ELK/Graphviz/xyflow impliqué.'])
pkg('dataviz-core','dataviz / état et builders','Tous exports actuels : modèle tabulaire, store/filtres/crossfilter/drill/bookmarks/URL, agrégats/calculs/pivots, palettes/formats, builders charts, annotations et layout dashboard.','Nom existant conservé ; cohésion état+data builders consommés par 4 adapters, aucune preuve justifiant leur éclatement immédiat.',subpaths=['.'],reuse='495 exports / 68 modules hors barrel, zéro runtime ; rapatrier sans refonte. CSV pur partagé depuis helper wrappers par tranche compatible.',proof='État et sérialisation, cross-view, 495 exports ; builders ≠ solveurs de layout ; aucun import canvas, DS ou DOM.',existing=True)
for fw in FW:
 pkg('dataviz-'+fw,'dataviz / adaptateurs','Store bridge '+fw+', tous wrappers charts/dashboard/filtres/actions/exports actuels ; controlled DS rendu, état core ; export visuel partagé sans modifier API.','Nom existant conservé avec son framework ; sémantique dashboard distincte de graph-canvas.',deps=['dataviz-core','design-system-'+fw,'design-system-themes','graph-export'],subpaths=['.'],reuse='Tout packages/dataviz-'+fw+' ; Angular inclut le seam signals, QueryBar et DateHistogramChart.',proof='Surface export source, lifecycle subscriptions, interactions WP20, tarballs/CSS/SSR ; parité mesurée par composant, pas par export transitif.',existing=True,env='Adapter '+fw+' ; peer framework',third=[])
for fw in FW:
 pkg('design-system-'+fw,'adaptateurs DS existants','Tous composants présentationnels DS existants, dont charts/graph legends/dashboard ; tokens et API contrôlée. Aucun store BI, aucun contrôleur canvas obligatoire.','Nom publié conservé ; les extensions graph-* consomment le DS, le DS ne dépend pas du workbench.',deps=['design-system-themes','graph-layout','graph-scene'],reuse='93 noms runtime graphiques distincts réemployés ; React Dashboard absent du barrel source.',proof='Régressions composants seuls ; calculs purs extraits via sous-chemins graph-layout/scene sans importer registry complète ; pas import graph-canvas/dataviz-core/recipes depuis barrel DS.',existing=True,env='Framework '+fw,third=['Dépendances manifest existantes (Lucide pour Svelte/React/Vue, peers frameworks) conservées ; inventaire local dans JSON.'])
pkg('design-system-tokens','contrats visuels existants','Sources tokens et types de thème ; contrats couleur/spacing/typographie.','Nom existant conservé ; aucune nouvelle palette concurrente.',proof='Résolution --st-* sans couleurs imposées par une recette.',existing=True)
pkg('design-system-themes','theming existant','Thèmes portables --st-* appliqués par adapters/hosts ; résolution vers valeurs de scène explicites.','Nom existant conservé ; backend peinture reçoit des valeurs résolues.',deps=['design-system-tokens'],proof='Thèmes clairs/sombres/tenant et ressources export reproductibles.',existing=True)

# Official feature labels map to behavior owners, not to vendor dependencies.
FEATURE_OWNERS={}
def features(owner,labels):
 for label in labels.split('|'):FEATURE_OWNERS[label]=owner
features('graph-canvas','Adjustable interactivity|Collapse & Expand|Constraints on movement|Copy & Paste|Drag & Drop|Element palette|Element tools|Events|Grid|Guidelines|Keyboard|Link tools|Minimap|Property editor & viewer|Selection|Shape transformation|Toggle visibility|Undo/Redo|Zoom & Pan|Save/Load')
features('graph-scene','Animation|Content-driven shapes|Custom shapes|External images|Geometry|Highlighters|Measurement|Text content|Vectorizer|Virtual rendering|Performance')
features('graph-routing','Anchors|Connection points|Connectors|Link labels|Link-to-link|Ports|Routers')
features('graph-model','Custom properties|Embedding|Graph API|Validation')
features('graph-layout','Automatic layout')
features('graph-profiles','Built-in shapes')
features('graph-codecs','Export to JSON|Import/Export|Visio')
features('graph-export','Export to PDF|Export to PNG/JPEG|Export to SVG|Print')
features('graph-dom','HTML shapes')
features('graph-recipes','Simulation|Integration')
# Visual UI feature owner = concrete adapter; framework peers contribute equally.
features('graph-svelte','CSS styling|Context Toolbar|Menus|Popups|Responsive|Toolbar|Tooltips')

CATEGORIES={
 'modeling':'''data-modeling bpmn-editor uml-class-diagrams use-case-diagram activity-diagram sequence-diagram uml-statechart-diagram parametric-diagram the-archimate-enterprise-architecture-modeling-language database visio-bpmn-import visio-bpmn-export visio-org-chart-import visio-flowchart-import bpmn-pools-swimlanes-milestones uml-class-shape-inspector'''.split(),
 'workflow':'''ai-workflow-builder ai-agent-builder marketing-automation workflow-builder chatbot flowchart image-processor decision-tree theory-of-change microservices-architecture discrete-event-system-specification finite-state-machines petri-nets dialog-generator animated-process-flow-diagram'''.split(),
 'hierarchy':'''organizational-chart corporate-organizational-chart mind-map chatgpt-mindmap tree-designer abstract-syntax-tree json-visualizer genogram fault-tree-analysis fishbone multidirectional-tree tree-graph-and-cycles decision-tree-analysis searchable-sitemap team-order tree-builder tree-of-life hierarchical-diagrams'''.split(),
 'planning':'''kanban planogram timeline yamazumi-3d sheet-cutting bryntum-integration marey-chart pert-chart tournament-brackets nodejs-milestones-timeline chatgpt-timeline tasks'''.split(),
 'simulation':'''scada dwdm-circuit logic-circuits electric-generator roi-calculator bandwidth puzzle chess constellation tokens counters dynamic-status-icons'''.split(),
 'layout':'''sankey-diagram data-mapping msagl-layout force-directed-layout container-layout elk-layout circular-layout rectangular-layout serpentine-layout elk-layout-with-ports-and-clusters directed-graph-layout hexagonal-grid force-directed-interaction force-directed-radial-force shortest-path-algorithm libavoid-standalone-link-routing smart-routing convex-hull-algorithm find-all-cells-between-2-elements'''.split(),
 'export':'''pdf-export saving-and-loading-using-file-system-access-api clipboard-api-integration'''.split(),
 'integration':'''framework-element-view charts diagram-generation-from-external-data font-awesome tabs bootstrap-tabs microsoft-adaptive-cards rough-shapes spreadsheet-shapes-with-handsontable'''.split(),
 'rendering':'''html-form-ports rich-text-editor element-tags-and-badges external-svg-images fills curves icons content-driven-shapes connector-arrows element-port-and-link-label-markup preserve-spaces-in-text-wrap scale-svgmarker dynamic-font-size absolute-port-layout-dynamic-port-sizes'''.split()
}
def category(slug):return next((k for k,v in CATEGORIES.items() if slug in v),'interaction')
