/**
 * Unit tests — git-flow branch-label legibility policy (SPEC_GITFLOW_LABELS,
 * ratified (b), Phases 1+2): P1.1 compaction table + ambiguity guard, P1.2
 * priority ordering + deterministic collision culling + hysteresis margin,
 * P1.3 interaction full-name labels (AC4), P2.1 LOD tiers with ±10%
 * hysteresis, P2.2 bounded fork→tip→stagger anchor fallback, AC5 determinism.
 */

import { describe, expect, it } from "vitest";
import {
  approximateLabelMeasure,
  compactGitFlowLabels,
  gitFlowLabelBoxHeightPx,
  compactGitFlowName,
  gitFlowNameHash,
  middleEllipsisPreservingSuffix,
  placeGitFlowLabels,
  resolveGitFlowLabelTier,
  DEFAULT_LABEL_MAX_CHARS,
  type GitFlowLabelCamera,
  type GitFlowLabelPolicyInput,
} from "../src/gitflow-labels";
import type { GitFlowBranchLabel } from "../src/layout-gitflow";
import { BOX_BASE_HEIGHT_PX } from "../src/render-geometry";

const CAMERA: GitFlowLabelCamera = { x: 0, y: 0, zoom: 1, width: 1600, height: 800 };

function label(partial: Partial<GitFlowBranchLabel> & { nodeIndex: number; name: string }): GitFlowBranchLabel {
  return {
    repo: "r",
    lane: 1,
    x: 0,
    y: 0,
    entry: "in-window",
    ...partial,
  };
}

function place(
  labels: GitFlowBranchLabel[],
  extra: Partial<Omit<GitFlowLabelPolicyInput, "labels" | "measure" | "camera">> & {
    camera?: Partial<GitFlowLabelCamera>;
  } = {},
  options = {},
) {
  return placeGitFlowLabels(
    {
      labels,
      measure: approximateLabelMeasure,
      camera: { ...CAMERA, ...extra.camera },
      interaction: extra.interaction,
      previous: extra.previous,
    },
    options,
  );
}

// ---------------------------------------------------------------------------
// P1.1 — compaction table.
// ---------------------------------------------------------------------------

describe("P1.1 semantic compaction", () => {
  it("compacts worktree-agent-<hash> to agent:<7hex> and demotes it", () => {
    const c = compactGitFlowName("worktree-agent-a2bfd3abf8ffc2032");
    expect(c.text).toBe("agent:a2bfd3a");
    expect(c.autogenerated).toBe(true);
    expect(compactGitFlowName("worktree-agent-ac2f8bac9020bc90b").text).toBe("agent:ac2f8ba");
  });

  it("compacts dependabot/<eco>/<pkg>-<ver> to deps:<pkg> and demotes it", () => {
    const c = compactGitFlowName("dependabot/npm_and_yarn/lodash-4.17.21");
    expect(c.text).toBe("deps:lodash");
    expect(c.autogenerated).toBe(true);
    expect(compactGitFlowName("dependabot/github_actions/actions/checkout-4").text).toBe(
      "deps:actions/checkout",
    );
  });

  it("strips refs/heads/ and origin/ then compacts conventional prefixes", () => {
    expect(compactGitFlowName("refs/heads/feature/cadrage").text).toBe("feat:cadrage");
    expect(compactGitFlowName("origin/fix/bug-123").text).toBe("fix:bug-123");
    expect(compactGitFlowName("feat/x")).toEqual({ text: "feat:x", autogenerated: false });
    expect(compactGitFlowName("chore/x").text).toBe("chore:x");
    expect(compactGitFlowName("hotfix/urgent").text).toBe("hotfix:urgent");
    expect(compactGitFlowName("release/1.2.0").text).toBe("rel:1.2.0");
  });

  it("leaves unconventional human names untouched", () => {
    expect(compactGitFlowName("b1-p2-edges")).toEqual({ text: "b1-p2-edges", autogenerated: false });
  });

  it("middle-ellipsis beyond ~22 chars PRESERVES the meaningful suffix", () => {
    const c = compactGitFlowName("feat/cadrage-geo-integration-extra-long");
    expect(c.text.length).toBeLessThanOrEqual(DEFAULT_LABEL_MAX_CHARS);
    expect(c.text.startsWith("feat:…")).toBe(true);
    expect(c.text.endsWith("extra-long")).toBe(true);
    // The raw helper keeps the tail when there is no compact prefix head.
    const raw = middleEllipsisPreservingSuffix("a-very-long-plain-branch-name-suffix", 22);
    expect(raw.length).toBe(22);
    expect(raw.endsWith("-suffix")).toBe(true);
  });

  it("ambiguity guard: distinct names colliding on one compacted string get hash suffixes", () => {
    const labels = [
      label({ nodeIndex: 0, name: "feat/one-CHANGED-part-geo-integration-suffix" }),
      label({ nodeIndex: 1, name: "feat/two-ALTERED-part-geo-integration-suffix" }),
    ];
    const [a, b] = compactGitFlowLabels(labels);
    expect(a!.text).not.toBe(b!.text);
    expect(a!.text).toMatch(/·[0-9a-f]{4}$/);
    expect(b!.text).toMatch(/·[0-9a-f]{4}$/);
    // Deterministic across calls.
    const again = compactGitFlowLabels(labels);
    expect(again.map((c) => c.text)).toEqual([a!.text, b!.text]);
  });

  it("ambiguity guard does NOT fire for identical full names (main per repo band)", () => {
    const labels = [
      label({ nodeIndex: 0, name: "main", repo: "a", lane: 0 }),
      label({ nodeIndex: 1, name: "main", repo: "b", lane: 0 }),
    ];
    const [a, b] = compactGitFlowLabels(labels);
    expect(a!.text).toBe("main");
    expect(b!.text).toBe("main");
  });

  it("configurable autogenerated rules extend the demoted class", () => {
    const c = compactGitFlowName("agy/run-42", {
      autogenerated: [{ pattern: /^agy\/run-(\d+)$/, replace: "agy:$1" }],
    });
    expect(c).toEqual({ text: "agy:42", autogenerated: true });
  });

  it("name hash is stable and deterministic", () => {
    expect(gitFlowNameHash("feat/alpha")).toBe(gitFlowNameHash("feat/alpha"));
    expect(gitFlowNameHash("feat/alpha")).not.toBe(gitFlowNameHash("feat/beta"));
  });
});

// ---------------------------------------------------------------------------
// P2.1 — LOD tiers with ±10% hysteresis.
// ---------------------------------------------------------------------------

describe("P2.1 zoom LOD tiers", () => {
  it("resolves base tiers without previous state", () => {
    expect(resolveGitFlowLabelTier(0.05)).toBe(0);
    expect(resolveGitFlowLabelTier(0.5)).toBe(1);
    expect(resolveGitFlowLabelTier(2.0)).toBe(2);
  });

  it("±10% hysteresis: the previous tier sticks inside the band", () => {
    // t1 default 0.3: from T0, zoom 0.31 (< 0.33) stays T0…
    expect(resolveGitFlowLabelTier(0.31, 0)).toBe(0);
    // …but a fresh camera at 0.31 is T1, and from T1 zoom 0.29 (> 0.27) stays T1.
    expect(resolveGitFlowLabelTier(0.31)).toBe(1);
    expect(resolveGitFlowLabelTier(0.29, 1)).toBe(1);
    // Leaving the band commits the change.
    expect(resolveGitFlowLabelTier(0.34, 0)).toBe(1);
    expect(resolveGitFlowLabelTier(0.26, 1)).toBe(0);
  });

  it("crosses multiple tiers in one jump", () => {
    expect(resolveGitFlowLabelTier(3.0, 0)).toBe(2);
    expect(resolveGitFlowLabelTier(0.01, 2)).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// P1.2 + P2.2 — priority, culling, anchor fallback, hysteresis margin.
// ---------------------------------------------------------------------------

describe("P1.2 priority collision culling + P2.2 anchor fallback", () => {
  it("higher priority wins a contested spot; fallback is bounded fork→tip→stagger", () => {
    // Three labels at (effectively) the SAME anchor and NO tip anchors: trunk
    // wins the fork slot, the newer feature takes the ONE stagger slot, the
    // older feature is CULLED — the fallback chain is bounded, no stacking.
    // (recency falls back to `x` when tipX is absent; 0.001 world ≈ 0 px.)
    const labels = [
      label({ nodeIndex: 0, name: "main", lane: 0, x: 0, y: 0 }),
      label({ nodeIndex: 1, name: "feat/old", x: 0, y: 0, tipX: undefined }),
      label({ nodeIndex: 2, name: "feat/new", x: 0.001, y: 0, tipX: undefined }),
    ];
    const p = place(labels);
    const byIndex = new Map(p.labels.map((l) => [l.nodeIndex, l]));
    expect(byIndex.get(0)?.anchor).toBe("fork");
    expect(byIndex.get(2)?.anchor).toBe("stagger"); // newer feature staggered
    expect(byIndex.has(1)).toBe(false); // older feature culled (bounded chain)
    expect(p.culled).toContain(1);
  });

  it("tip-right fallback places a label whose fork region is saturated", () => {
    const labels = [
      label({ nodeIndex: 0, name: "main", lane: 0, x: 0, y: 0, tipX: 600 }),
      // Same anchor as main, but a far tip: falls back to the tip anchor.
      label({ nodeIndex: 1, name: "feat/far-tip", x: 0, y: 0, tipX: 400 }),
    ];
    const p = place(labels);
    const far = p.labels.find((l) => l.nodeIndex === 1);
    expect(far?.anchor).toBe("tip");
    // Tip-anchored pill sits RIGHT of the tip x (clearance + half width).
    expect(far!.screenX).toBeGreaterThan((400 - CAMERA.x) * CAMERA.zoom + CAMERA.width / 2);
  });

  it("I1: accepted AABBs never intersect, even under heavy pressure", () => {
    const labels: GitFlowBranchLabel[] = [];
    for (let i = 0; i < 60; i += 1) {
      labels.push(
        label({
          nodeIndex: i,
          name: `feat/branch-${String(i).padStart(2, "0")}`,
          x: (i % 6) * 30,
          y: Math.floor(i / 6) * 6,
          tipX: (i % 6) * 30 + 120,
        }),
      );
    }
    const p = place(labels);
    expect(p.labels.length).toBeGreaterThan(0);
    expect(p.culled.length).toBeGreaterThan(0); // pressure actually culled
    for (let a = 0; a < p.labels.length; a += 1) {
      for (let b = a + 1; b < p.labels.length; b += 1) {
        const A = p.labels[a]!;
        const B = p.labels[b]!;
        const overlap =
          Math.abs(A.screenX - B.screenX) < (A.w + B.w) / 2 &&
          Math.abs(A.screenY - B.screenY) < (A.h + B.h) / 2;
        expect(overlap, `${A.text} vs ${B.text}`).toBe(false);
      }
    }
  });

  it("AC5 determinism: same scene + camera + state ⇒ identical label set", () => {
    const labels: GitFlowBranchLabel[] = [];
    for (let i = 0; i < 40; i += 1) {
      labels.push(
        label({
          nodeIndex: i,
          name: i % 3 === 0 ? `worktree-agent-${i.toString(16).padStart(7, "0")}abcdef` : `feat/b${i}`,
          x: (i % 5) * 25,
          y: Math.floor(i / 5) * 8,
          tipX: (i % 5) * 25 + 90,
        }),
      );
    }
    const run = () => place(labels, { camera: { zoom: 2 } });
    const a = run();
    const b = run();
    expect(JSON.stringify(a.labels)).toBe(JSON.stringify(b.labels));
    expect([...a.placed].sort()).toEqual([...b.placed].sort());
    expect(a.culled).toEqual(b.culled);
    expect(a.tier).toBe(2);
  });

  it("hysteresis margin: a previously-placed label keeps a knife-edge slot a new one would not get", () => {
    // Pill A at x=0; pill B's fork sits so the gap is ~4 px — inside the 8 px
    // new-label margin but NOT overlapping. Stagger for B is blocked by C.
    const mkLabels = () => [
      label({ nodeIndex: 0, name: "main", lane: 0, x: 0, y: 0 }),
      label({ nodeIndex: 1, name: "bb", x: 40, y: 0, tipX: undefined }),
    ];
    // Compute A's half width to position B at a ~4 px edge gap: instead of
    // arithmetic, probe behaviourally — B new ⇒ falls to stagger; B previously
    // placed ⇒ keeps the fork slot.
    const fresh = place(mkLabels());
    const bFresh = fresh.labels.find((l) => l.nodeIndex === 1);
    const kept = place(mkLabels(), { previous: { tier: fresh.tier, placed: new Set([0, 1]) } });
    const bKept = kept.labels.find((l) => l.nodeIndex === 1);
    expect(bFresh).toBeDefined();
    expect(bKept).toBeDefined();
    // The previously-placed run must never be MORE demoted than the fresh run.
    const order = { fork: 0, tip: 1, stagger: 2 } as const;
    expect(order[bKept!.anchor]).toBeLessThanOrEqual(order[bFresh!.anchor]);
    // And with a knife-edge gap, the anchors actually differ.
    const gapLabels = [
      label({ nodeIndex: 0, name: "wwwwwwww", lane: 0, x: 0, y: 0 }),
      label({ nodeIndex: 1, name: "wwwwwwww2", x: 0, y: 0, tipX: undefined }),
    ];
    // Same anchor: without previous, label 1 staggers; previously placed at
    // the stagger slot it keeps it — margins never let it OVERLAP label 0.
    const g1 = place(gapLabels);
    expect(g1.labels.find((l) => l.nodeIndex === 1)?.anchor).toBe("stagger");
  });
});

// ---------------------------------------------------------------------------
// P2.1 tier gating + P1.3 interaction (AC2 analog / AC4).
// ---------------------------------------------------------------------------

describe("tier gating and interaction full names", () => {
  const scene = () => [
    label({ nodeIndex: 0, name: "main", lane: 0, x: 0, y: 0, tipX: 600 }),
    label({ nodeIndex: 1, name: "release/1.2", x: 60, y: 44, tipX: 240 }),
    label({ nodeIndex: 2, name: "feat/human-branch", x: 120, y: 88, tipX: 300 }),
    label({ nodeIndex: 3, name: "worktree-agent-abcdef0123456789a", x: 180, y: 132, tipX: 360 }),
    label({ nodeIndex: 4, name: "v-tag-ref", lane: -1, x: 600, y: 20, entry: "tip-only", tipX: 600 }),
  ];

  it("T0 (far): trunk + interaction only", () => {
    const p = place(scene(), { camera: { zoom: 0.05 } });
    expect(p.tier).toBe(0);
    expect(p.labels.map((l) => l.nodeIndex)).toEqual([0]);
  });

  it("T1 (mid): + human branches, still NO autogenerated pill (AC2 analog)", () => {
    const p = place(scene(), { camera: { zoom: 0.6 } });
    expect(p.tier).toBe(1);
    const ids = p.labels.map((l) => l.nodeIndex);
    expect(ids).toContain(0);
    expect(ids).toContain(1);
    expect(ids).toContain(2);
    expect(ids).toContain(4);
    expect(ids).not.toContain(3);
    expect(p.labels.some((l) => l.text.startsWith("agent:"))).toBe(false);
  });

  it("T2 (near): + autogenerated in compacted agent:<hash> form", () => {
    const p = place(scene(), { camera: { zoom: 2 } });
    expect(p.tier).toBe(2);
    const agent = p.labels.find((l) => l.nodeIndex === 3);
    expect(agent?.text).toBe("agent:abcdef0");
    expect(agent?.cls).toBe("autogenerated");
  });

  it("AC4: a culled/demoted branch marked SELECTED renders its full name at any tier", () => {
    const p = place(scene(), { camera: { zoom: 0.05 }, interaction: { selected: new Set([3]) } });
    expect(p.tier).toBe(0);
    const sel = p.labels.find((l) => l.nodeIndex === 3);
    expect(sel).toBeDefined();
    expect(sel!.fullName).toBe(true);
    expect(sel!.text).toBe("worktree-agent-abcdef0123456789a");
    expect(sel!.cls).toBe("interaction");
  });

  it("hovered and searched behave like selected (P1.3)", () => {
    const hov = place(scene(), { camera: { zoom: 0.05 }, interaction: { hovered: [3] } });
    expect(hov.labels.some((l) => l.nodeIndex === 3 && l.fullName)).toBe(true);
    const sea = place(scene(), { camera: { zoom: 0.05 }, interaction: { searched: [2] } });
    expect(sea.labels.some((l) => l.nodeIndex === 2 && l.text === "feat/human-branch")).toBe(true);
  });

  it("priority order: interaction ▸ trunk ▸ release ▸ feature ▸ tip-ref (acceptance order)", () => {
    const p = place(scene(), { camera: { zoom: 0.6 }, interaction: { selected: [2] } });
    const classes = p.labels.map((l) => l.cls);
    const firstOf = (c: string) => classes.indexOf(c as never);
    expect(firstOf("interaction")).toBe(0);
    expect(firstOf("trunk")).toBeGreaterThan(firstOf("interaction"));
    expect(firstOf("release")).toBeGreaterThan(firstOf("trunk"));
    expect(firstOf("tip-ref")).toBeGreaterThan(firstOf("release"));
  });

  it("feature recency: the newer tip places first within the class", () => {
    const labels = [
      label({ nodeIndex: 0, name: "feat/older", x: 0, y: 0, tipX: 100 }),
      label({ nodeIndex: 1, name: "feat/newer", x: 300, y: 0, tipX: 500 }),
    ];
    const p = place(labels);
    expect(p.labels[0]!.nodeIndex).toBe(1);
  });
});

// ---------------------------------------------------------------------------
// Label scale (−20% principal verdict, 2026-07-05): pills shrink font+padding
// together and the collision AABBs use the SHRUNKEN boxes.
// ---------------------------------------------------------------------------

describe("labelScale (−20% pills)", () => {
  it("gitFlowLabelBoxHeightPx: default 0.8 × legacy height; explicit overrides win", () => {
    expect(gitFlowLabelBoxHeightPx()).toBeCloseTo(BOX_BASE_HEIGHT_PX * 0.8, 10);
    expect(gitFlowLabelBoxHeightPx({ labelScale: 1 })).toBe(BOX_BASE_HEIGHT_PX);
    expect(gitFlowLabelBoxHeightPx({ labelScale: 0.5 })).toBeCloseTo(BOX_BASE_HEIGHT_PX * 0.5, 10);
    expect(gitFlowLabelBoxHeightPx({ boxHeightPx: 12, labelScale: 1 })).toBe(12);
  });

  it("placed pill AABBs shrink exactly 20% (height AND width) vs labelScale 1", () => {
    const labels = [label({ nodeIndex: 0, name: "feat/some-branch", x: 0, y: 0 })];
    const legacy = place(labels, {}, { labelScale: 1 }).labels[0]!;
    const scaled = place(labels).labels[0]!; // default labelScale 0.8
    expect(scaled.h).toBeCloseTo(legacy.h * 0.8, 6);
    expect(scaled.w).toBeCloseTo(legacy.w * 0.8, 6);
    // The culling used the SHRUNKEN box: at 0.8 the AABB is strictly smaller.
    expect(scaled.h).toBeCloseTo(BOX_BASE_HEIGHT_PX * 0.8, 6); // zoom 1, pr 1
  });

  it("shrunken pills relieve collision pressure (more labels survive culling)", () => {
    const labels: GitFlowBranchLabel[] = [];
    for (let i = 0; i < 40; i += 1) {
      labels.push(
        label({
          nodeIndex: i,
          name: `feat/branch-${String(i).padStart(2, "0")}`,
          x: (i % 6) * 30,
          y: Math.floor(i / 6) * 6,
          tipX: (i % 6) * 30 + 120,
        }),
      );
    }
    const scaled = place(labels); // default 0.8
    const legacy = place(labels, {}, { labelScale: 1 });
    expect(scaled.labels.length).toBeGreaterThanOrEqual(legacy.labels.length);
  });
});
