import { describe, expect, it, vi } from "vitest";
import { mount } from "@vue/test-utils";
import {
  Autosave,
  Calendar,
  Rating,
  SlideIndicator,
  TimePicker,
} from "./index.js";

// Invariants mirrored from the Svelte/React sources for the specialized
// components ported to Vue.

describe("Rating", () => {
  it("renders a radiogroup with `max` radio stars", () => {
    const wrapper = mount(Rating, { props: { max: 5, value: 0 } });
    expect(wrapper.find('[role="radiogroup"]').exists()).toBe(true);
    expect(wrapper.findAll('[role="radio"]')).toHaveLength(5);
  });

  it("marks filled stars and aria-checks the current value", () => {
    const wrapper = mount(Rating, { props: { value: 3, max: 5 } });
    expect(wrapper.findAll(".st-rating__star--full")).toHaveLength(3);
    const radios = wrapper.findAll('[role="radio"]');
    expect(radios[2].attributes("aria-checked")).toBe("true");
  });

  it("emits the clicked value via onChange prop and change event", async () => {
    const onChange = vi.fn();
    const wrapper = mount(Rating, { props: { value: 0, max: 5, onChange } });
    await wrapper.findAll('[role="radio"]')[3].trigger("click");
    expect(onChange).toHaveBeenCalledWith(4);
    expect(wrapper.emitted("change")?.[0]).toEqual([4]);
  });

  it("re-clicking the current value resets to 0", async () => {
    const onChange = vi.fn();
    const wrapper = mount(Rating, { props: { value: 4, max: 5, onChange } });
    await wrapper.findAll('[role="radio"]')[3].trigger("click");
    expect(onChange).toHaveBeenCalledWith(0);
  });

  it("supports half-step keyboard increments when allowHalf", async () => {
    const onChange = vi.fn();
    const wrapper = mount(Rating, {
      props: { value: 2, max: 5, allowHalf: true, onChange },
    });
    await wrapper.findAll('[role="radio"]')[1].trigger("keydown", { key: "ArrowRight" });
    expect(onChange).toHaveBeenCalledWith(2.5);
  });

  it("does not emit when readonly", async () => {
    const onChange = vi.fn();
    const wrapper = mount(Rating, { props: { value: 2, readonly: true, onChange } });
    await wrapper.findAll('[role="radio"]')[3].trigger("click");
    expect(onChange).not.toHaveBeenCalled();
    expect(wrapper.find('[role="radiogroup"]').attributes("aria-readonly")).toBe("true");
  });

  it("works uncontrolled (internal state) when value omitted", async () => {
    const onChange = vi.fn();
    const wrapper = mount(Rating, { props: { max: 5, onChange } });
    await wrapper.findAll('[role="radio"]')[2].trigger("click");
    expect(onChange).toHaveBeenCalledWith(3);
    expect(wrapper.findAll(".st-rating__star--full")).toHaveLength(3);
  });
});

describe("TimePicker", () => {
  it("renders a combobox closed by default", () => {
    const wrapper = mount(TimePicker, { props: { value: "" } });
    expect(wrapper.find('[role="combobox"]').exists()).toBe(true);
    expect(wrapper.find('[role="listbox"]').exists()).toBe(false);
  });

  it("opens a listbox of slots generated by step", async () => {
    const wrapper = mount(TimePicker, {
      props: { value: "", step: 60, min: "09:00", max: "11:00" },
    });
    await wrapper.find('[role="combobox"]').trigger("click");
    const options = wrapper.findAll('[role="option"]');
    expect(options.map((o) => o.text())).toEqual(["09:00", "10:00", "11:00"]);
  });

  it("emits HH:mm 24h value even when format is 12 (display only)", async () => {
    const onChange = vi.fn();
    const wrapper = mount(TimePicker, {
      props: { value: "", step: 60, min: "13:00", max: "14:00", format: "12", onChange },
    });
    await wrapper.find('[role="combobox"]').trigger("click");
    const options = wrapper.findAll('[role="option"]');
    expect(options[0].text()).toBe("01:00 PM");
    await options[0].trigger("click");
    expect(onChange).toHaveBeenCalledWith("13:00");
    expect(wrapper.emitted("change")?.[0]).toEqual(["13:00"]);
  });

  it("does not open when disabled", async () => {
    const wrapper = mount(TimePicker, { props: { value: "", disabled: true } });
    await wrapper.find('[role="combobox"]').trigger("click");
    expect(wrapper.find('[role="listbox"]').exists()).toBe(false);
  });
});

describe("Calendar", () => {
  it("renders an inline grid of 42 day cells", () => {
    const wrapper = mount(Calendar, { props: { value: "2024-03-15", month: "2024-03" } });
    expect(wrapper.find('[role="grid"]').exists()).toBe(true);
    expect(wrapper.findAll('[role="gridcell"]')).toHaveLength(42);
  });

  it("emits a YYYY-MM-DD string on day click (local time)", async () => {
    const onChange = vi.fn();
    const wrapper = mount(Calendar, {
      props: { value: "2024-03-01", month: "2024-03", onChange },
    });
    const cells = wrapper.findAll('[role="gridcell"]');
    const target = cells.find((c) => c.text() === "15" && !c.classes("st-calendar__day--outside"));
    await target!.trigger("click");
    expect(onChange).toHaveBeenCalledWith("2024-03-15");
  });

  it("disables out-of-bounds dates via min/max", () => {
    const wrapper = mount(Calendar, {
      props: { value: "2024-03-15", month: "2024-03", min: "2024-03-10", max: "2024-03-20" },
    });
    const cells = wrapper.findAll('[role="gridcell"]');
    const before = cells.find(
      (c) => c.text() === "5" && !c.classes("st-calendar__day--outside"),
    );
    expect((before!.element as HTMLButtonElement).disabled).toBe(true);
  });

  it("builds a [start, end] tuple in range mode", async () => {
    const onChange = vi.fn();
    const wrapper = mount(Calendar, {
      props: { value: ["2024-03-05", null], month: "2024-03", range: true, onChange },
    });
    const cells = wrapper.findAll('[role="gridcell"]');
    const end = cells.find((c) => c.text() === "12" && !c.classes("st-calendar__day--outside"));
    await end!.trigger("click");
    expect(onChange).toHaveBeenCalledWith(["2024-03-05", "2024-03-12"]);
  });

  it("navigates months with the next button", async () => {
    const wrapper = mount(Calendar, { props: { value: "2024-03-15", month: "2024-03" } });
    await wrapper.find('[aria-label="Mois suivant"]').trigger("click");
    expect(wrapper.find(".st-calendar__monthLabel").text().toLowerCase()).toContain("avril");
  });
});

describe("SlideIndicator", () => {
  it("renders a tablist of `count` tabs", () => {
    const wrapper = mount(SlideIndicator, { props: { count: 4 } });
    expect(wrapper.find('[role="tablist"]').exists()).toBe(true);
    expect(wrapper.findAll('[role="tab"]')).toHaveLength(4);
  });

  it("applies roving tabindex on the current tab", () => {
    const wrapper = mount(SlideIndicator, { props: { count: 4, current: 2 } });
    const tabs = wrapper.findAll('[role="tab"]');
    expect(tabs[2].attributes("tabindex")).toBe("0");
    expect(tabs[0].attributes("tabindex")).toBe("-1");
    expect(tabs[2].attributes("aria-selected")).toBe("true");
  });

  it("emits the target index on click and arrow keys", async () => {
    const onChange = vi.fn();
    const wrapper = mount(SlideIndicator, { props: { count: 4, current: 1, onChange } });
    await wrapper.findAll('[role="tab"]')[3].trigger("click");
    expect(onChange).toHaveBeenCalledWith(3);
    await wrapper.findAll('[role="tab"]')[1].trigger("keydown", { key: "ArrowRight" });
    expect(onChange).toHaveBeenCalledWith(2);
    expect(wrapper.emitted("change")).toBeTruthy();
  });
});

describe("Autosave", () => {
  it("uses role=status outside of error", () => {
    const wrapper = mount(Autosave, { props: { status: "saved" } });
    expect(wrapper.find('[role="status"]').exists()).toBe(true);
  });

  it("uses role=alert on error and shows a retry button when onRetry given", async () => {
    const onRetry = vi.fn();
    const wrapper = mount(Autosave, { props: { status: "error", onRetry } });
    expect(wrapper.find('[role="alert"]').exists()).toBe(true);
    const btn = wrapper.find(".st-autosave__retry");
    expect(btn.exists()).toBe(true);
    await btn.trigger("click");
    expect(onRetry).toHaveBeenCalled();
    expect(wrapper.emitted("retry")).toBeTruthy();
  });

  it("renders overridable labels", () => {
    const wrapper = mount(Autosave, {
      props: { status: "saving", labels: { saving: "Custom saving" } },
    });
    expect(wrapper.find(".st-autosave__label").text()).toBe("Custom saving");
  });

  it("renders a relative time on saved", () => {
    const wrapper = mount(Autosave, {
      props: { status: "saved", lastSaved: new Date(Date.now() - 60_000) },
    });
    expect(wrapper.find(".st-autosave__time").exists()).toBe(true);
  });
});
