import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compileThemeWithModes, entropicTheme, forgeTheme, sentTechTheme } from "../dist/index.js";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const cssDir = join(root, "css");

const themes = [sentTechTheme, forgeTheme, entropicTheme];

mkdirSync(cssDir, { recursive: true });

for (const theme of themes) {
  const content = [
    "/* Generated by packages/themes/scripts/build-css.mjs. */",
    `/* Theme: ${theme.label} (${theme.id}) */`,
    `/* Dark mode: ${theme.tokensDark ? "3 blocks (light + auto + explicit)" : "none (light only)"} */`,
    compileThemeWithModes(theme)
  ].join("\n");

  writeFileSync(join(cssDir, `${theme.id}.css`), content);
}
