/**
 * GIT-FLOW branch-label LEGIBILITY POLICY (SPEC_GITFLOW_LABELS.md, ratified
 * (b) — Phases 1+2 together). A pure CPU-side label PRE-PASS that runs before
 * the existing `boxDimensions`/overlay draw path, per camera change:
 *
 *   branchLabels (layout anchors) ──compaction──▶ priority ──▶ placement
 *
 * and returns the PLACED label set the app/fixture builder actually emits.
 * The renderer is untouched (I4): callers simply feed fewer/renamed labels.
 *
 * Invariants implemented here:
 *   • I1 — ZERO OVERLAP: labels are placed in priority order against a
 *     screen-space occupancy grid; anything that would overlap an accepted
 *     pill AABB is dropped (MapLibre-style hard rule). Overlap is never
 *     "allowed a little".
 *   • I2 — the policy only decides NAMES; lanes/commits/connectors are the
 *     layout+renderer's business and always draw. A culled/demoted branch is
 *     reported as NOT placed — the caller renders its anchor as an EMPTY pill
 *     (or nothing), never hides its geometry.
 *   • I3 — hovered / selected / search-matched branches render their FULL,
 *     uncompacted name at TOP priority. (In the degenerate corner where two
 *     interaction labels overlap EACH OTHER, I1 wins — zero overlap is the
 *     hard invariant — deterministically by the stable sort key.)
 *   • I4 — pure functions, no renderer/shader/scene-contract coupling; every
 *     brick (compaction, tiers, culling, anchors) is independently usable.
 *   • I5 — nothing here ever touches lane geometry to "make room".
 *
 * Phase 1: P1.1 semantic compaction + autogenerated demotion (configurable
 * rules), P1.2 priority collision culling with an ~8 px hysteresis margin,
 * P1.3 interaction full-name labels. Phase 2: P2.1 zoom LOD tiers T0/T1/T2
 * with ±10% hysteresis, P2.2 bounded anchor fallback fork → tip → ONE stagger
 * slot.
 *
 * DETERMINISTIC (I4/AC5): no Date.now, no Math.random — the same scene +
 * camera (+ previous state) always yields the identical label set.
 */

import type { GitFlowBranchLabel } from "./layout-gitflow";
import { BOX_BASE_HEIGHT_PX, boxDimensions } from "./render-geometry";

// ---------------------------------------------------------------------------
// Options & defaults (P1.1 — configurable, spec-mandated defaults).
// ---------------------------------------------------------------------------

/** An autogenerated-branch pattern: matched names are COMPACTED and DEMOTED. */
export interface GitFlowAutogeneratedRule {
  /** Applied to the prefix-stripped name. Use capture groups for `replace`. */
  pattern: RegExp;
  /** Display template; `$1`…`$9` reference capture groups. */
  replace: string;
}

/** No-information prefixes stripped before any other compaction (P1.1). */
export const DEFAULT_STRIP_PREFIXES: readonly string[] = ["refs/heads/", "origin/"];

/** Conventional prefix compaction map (P1.1), longest prefix first. */
export const DEFAULT_PREFIX_COMPACTION: Readonly<Record<string, string>> = {
  "feature/": "feat:",
  "feat/": "feat:",
  "fix/": "fix:",
  "chore/": "chore:",
  "hotfix/": "hotfix:",
  "release/": "rel:",
};

/**
 * Default autogenerated patterns (P1.1):
 *   • `worktree-agent-<hash>` → `agent:<7hex>`;
 *   • `dependabot/<eco>/<pkg>-<ver>` → `deps:<pkg>`.
 * The DEMOTION is the class, not the rewrite: matched branches get NO
 * persistent pill at T0/T1 — names are hover/selection-first (T2 shows the
 * compacted form, still culling-gated).
 */
export const DEFAULT_AUTOGENERATED_RULES: readonly GitFlowAutogeneratedRule[] = [
  { pattern: /^worktree-agent-([0-9a-f]{7})[0-9a-f]*$/i, replace: "agent:$1" },
  { pattern: /^dependabot\/[^/]+\/(.+?)[-_]v?\d[\w.-]*$/, replace: "deps:$1" },
];

/** Width budget: middle-ellipsis beyond this many characters (P1.1). */
export const DEFAULT_LABEL_MAX_CHARS = 22;
/** Collision hysteresis margin in device px (P1.2): a NEW label needs this
 * extra clearance; an ALREADY-PLACED one only needs zero overlap, so panning
 * doesn't flicker labels on the knife edge. */
export const DEFAULT_HYSTERESIS_MARGIN_PX = 8;
/**
 * Branch-label pill SCALE relative to the legacy box glyph (principal verdict
 * 2026-07-05: "les labels sont encore un peu grands — 20% de trop"). Applied
 * to the pill BASE HEIGHT, which drives font + padding + measured width
 * together, so the collision AABBs and the drawn pills shrink IN SYNC.
 * Callers hand the SAME resolved height to the renderer via
 * {@link gitFlowLabelBoxHeightPx} → `GraphRendererOptions.boxBaseHeightPx`.
 */
export const DEFAULT_GITFLOW_LABEL_SCALE = 0.8;
/** Camera zoom at which T0 (far) hands over to T1 (mid) — P2.1. */
export const DEFAULT_TIER1_ZOOM = 0.3;
/** Camera zoom at which T1 (mid) hands over to T2 (near) — P2.1. */
export const DEFAULT_TIER2_ZOOM = 1.2;
/** ±10% tier hysteresis (P2.1): no popping storms while zooming. */
export const DEFAULT_TIER_HYSTERESIS_RATIO = 0.1;
/** Horizontal clearance (CSS px, × pixelRatio × zoom) a tip-anchored pill
 * keeps off the tip commit glyph (P2.2). */
export const DEFAULT_TIP_CLEARANCE_PX = 10;
/**
 * Vertical gap (device px) of the ONE bounded stagger slot (P2.2). MUST clear
 * {@link DEFAULT_HYSTERESIS_MARGIN_PX}, otherwise a NEW label staggering away
 * from a pill at its own fork anchor could never pass the margin test and the
 * slot would be unreachable.
 */
export const DEFAULT_STAGGER_GAP_PX = 10;

export interface GitFlowLabelPolicyOptions {
  /** Prefixes stripped verbatim (default {@link DEFAULT_STRIP_PREFIXES}). */
  stripPrefixes?: readonly string[];
  /** Conventional prefix → compact form (default {@link DEFAULT_PREFIX_COMPACTION}). */
  prefixMap?: Readonly<Record<string, string>>;
  /** Autogenerated patterns (default {@link DEFAULT_AUTOGENERATED_RULES}). */
  autogenerated?: readonly GitFlowAutogeneratedRule[];
  /** Middle-ellipsis budget in characters (default 22). */
  maxChars?: number;
  /** Collision hysteresis margin in device px (default 8). */
  hysteresisMarginPx?: number;
  /** T0→T1 zoom threshold (default {@link DEFAULT_TIER1_ZOOM}). */
  tier1Zoom?: number;
  /** T1→T2 zoom threshold (default {@link DEFAULT_TIER2_ZOOM}). */
  tier2Zoom?: number;
  /** Tier hysteresis ratio (default 0.1 = ±10%). */
  tierHysteresisRatio?: number;
  /** Pill SCALE relative to the legacy box glyph (default
   * {@link DEFAULT_GITFLOW_LABEL_SCALE} = 0.8, the −20% principal verdict).
   * Ignored when `boxHeightPx` is given explicitly. */
  labelScale?: number;
  /** Pill base height in CSS px (default {@link BOX_BASE_HEIGHT_PX} ×
   * `labelScale` — the SAME metric the renderer must draw with
   * (`boxBaseHeightPx`), so policy AABBs == drawn pills). */
  boxHeightPx?: number;
  /** Tip-anchor clearance in CSS px (default 10). */
  tipClearancePx?: number;
  /** Stagger-slot vertical gap in device px (default 2). */
  staggerGapPx?: number;
}

// ---------------------------------------------------------------------------
// P1.1 — semantic name compaction + autogenerated demotion.
// ---------------------------------------------------------------------------

/** Deterministic djb2-xor name hash (stable sort key + ambiguity suffix). */
export function gitFlowNameHash(name: string): number {
  let h = 5381;
  for (let i = 0; i < name.length; i += 1) {
    h = (Math.imul(h, 33) ^ name.charCodeAt(i)) >>> 0;
  }
  return h >>> 0;
}

const ELLIPSIS = "…";

/**
 * Width-budget MIDDLE ellipsis that PRESERVES the meaningful SUFFIX
 * (`feat:…-geo-integration`, never `feat:cadrage-geo-…`). A compact prefix
 * (`feat:` etc.) survives as the head when present; the tail keeps every
 * character the budget allows.
 */
export function middleEllipsisPreservingSuffix(text: string, maxChars: number): string {
  if (maxChars <= 1 || text.length <= maxChars) return text;
  const colon = text.indexOf(":");
  const head = colon > 0 && colon < 8 ? text.slice(0, colon + 1) : "";
  const budget = Math.max(1, maxChars - head.length - 1);
  return head + ELLIPSIS + text.slice(text.length - budget);
}

export interface CompactedGitFlowName {
  /** Compacted display text (before the cross-set ambiguity guard). */
  text: string;
  /** True when an autogenerated rule matched — the DEMOTED class (P1.1). */
  autogenerated: boolean;
}

/** Compact ONE branch name (strip → autogenerated rewrite → prefix → ellipsis). */
export function compactGitFlowName(
  name: string,
  options: GitFlowLabelPolicyOptions = {},
): CompactedGitFlowName {
  const strip = options.stripPrefixes ?? DEFAULT_STRIP_PREFIXES;
  const prefixMap = options.prefixMap ?? DEFAULT_PREFIX_COMPACTION;
  const rules = options.autogenerated ?? DEFAULT_AUTOGENERATED_RULES;
  const maxChars = options.maxChars ?? DEFAULT_LABEL_MAX_CHARS;

  let text = name;
  let stripped = true;
  while (stripped) {
    stripped = false;
    for (const p of strip) {
      if (text.startsWith(p) && text.length > p.length) {
        text = text.slice(p.length);
        stripped = true;
      }
    }
  }

  for (const rule of rules) {
    const match = rule.pattern.exec(text);
    if (match) {
      const rewritten = rule.replace.replace(/\$(\d)/g, (_, d: string) => match[Number(d)] ?? "");
      return { text: middleEllipsisPreservingSuffix(rewritten, maxChars), autogenerated: true };
    }
  }

  for (const prefix of Object.keys(prefixMap)) {
    if (text.startsWith(prefix) && text.length > prefix.length) {
      text = prefixMap[prefix]! + text.slice(prefix.length);
      break;
    }
  }

  return { text: middleEllipsisPreservingSuffix(text, maxChars), autogenerated: false };
}

export interface CompactedGitFlowLabel {
  /** Index of the Branch node in the layout input order (branchLabels key). */
  nodeIndex: number;
  /** The FULL, uncompacted branch name (I3 renders this on interaction). */
  fullName: string;
  /** Compacted + ellipsized + disambiguated display text. */
  text: string;
  autogenerated: boolean;
}

/**
 * Compact a WHOLE label set with the AMBIGUITY GUARD (P1.1): when two
 * DIFFERENT full names collide on the same compacted string, each gets a
 * short deterministic hash suffix. Two branches that genuinely share a full
 * name (e.g. `main` in two repo bands) are NOT ambiguous and keep the clean
 * text. Compaction is camera-independent, so display texts are stable across
 * zoom/pan.
 */
export function compactGitFlowLabels(
  labels: readonly GitFlowBranchLabel[],
  options: GitFlowLabelPolicyOptions = {},
): CompactedGitFlowLabel[] {
  const out: CompactedGitFlowLabel[] = labels.map((label) => {
    const { text, autogenerated } = compactGitFlowName(label.name, options);
    return { nodeIndex: label.nodeIndex, fullName: label.name, text, autogenerated };
  });

  const byText = new Map<string, CompactedGitFlowLabel[]>();
  for (const c of out) {
    const list = byText.get(c.text);
    if (list) list.push(c);
    else byText.set(c.text, [c]);
  }
  for (const group of byText.values()) {
    const distinct = new Set(group.map((c) => c.fullName));
    if (distinct.size <= 1) continue; // identical full names: not ambiguous
    for (const c of group) {
      const suffix = (gitFlowNameHash(c.fullName) % 0x10000).toString(16).padStart(4, "0");
      c.text = `${c.text}·${suffix}`;
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// P2.1 — zoom LOD tiers with ±10% hysteresis.
// ---------------------------------------------------------------------------

export type GitFlowLabelTier = 0 | 1 | 2;

/**
 * Resolve the LOD tier for a camera zoom. With a `previousTier`, thresholds
 * get a ±`tierHysteresisRatio` band: moving UP requires zoom ≥ threshold ×
 * (1 + h), moving DOWN requires zoom ≤ threshold × (1 − h) — inside the band
 * the previous tier STICKS (no popping storms while zooming, P2.1).
 */
export function resolveGitFlowLabelTier(
  zoom: number,
  previousTier?: GitFlowLabelTier,
  options: GitFlowLabelPolicyOptions = {},
): GitFlowLabelTier {
  const t1 = options.tier1Zoom ?? DEFAULT_TIER1_ZOOM;
  const t2 = options.tier2Zoom ?? DEFAULT_TIER2_ZOOM;
  const h = options.tierHysteresisRatio ?? DEFAULT_TIER_HYSTERESIS_RATIO;
  if (previousTier === undefined) {
    return zoom < t1 ? 0 : zoom < t2 ? 1 : 2;
  }
  const boundary = (from: GitFlowLabelTier): number => (from === 0 ? t1 : t2);
  let tier = previousTier;
  while (tier < 2 && zoom >= boundary(tier) * (1 + h)) tier = (tier + 1) as GitFlowLabelTier;
  while (tier > 0 && zoom <= boundary((tier - 1) as GitFlowLabelTier) * (1 - h)) {
    tier = (tier - 1) as GitFlowLabelTier;
  }
  return tier;
}

// ---------------------------------------------------------------------------
// P1.2 + P1.3 + P2.2 — priority, collision culling, anchors.
// ---------------------------------------------------------------------------

/** Priority class, descending priority order (P1.2). */
export type GitFlowLabelClass =
  | "interaction" // hovered / selected / search-matched (I3, never demoted)
  | "trunk" // main/master/develop label, one per repo band
  | "release" // release/* + hotfix/*
  | "feature" // human feature branches (recency-weighted)
  | "tip-ref" // tip-only refs
  | "autogenerated"; // demoted class — present at T2 only

const CLASS_RANK: Readonly<Record<GitFlowLabelClass, number>> = {
  interaction: 0,
  trunk: 1,
  release: 2,
  feature: 3,
  "tip-ref": 4,
  autogenerated: 5,
};

/** Camera + viewport: the SAME screen transform the renderer applies —
 * `screen = (world − camera) · zoom + viewport/2` in DEVICE px. */
export interface GitFlowLabelCamera {
  x: number;
  y: number;
  zoom: number;
  /** Canvas backing-store width/height in DEVICE px. */
  width: number;
  height: number;
  /** Device pixel ratio (pill metrics scale with pixelRatio × zoom). */
  pixelRatio?: number;
}

/** Interaction state (P1.3): members render FULL-NAME at top priority. */
export interface GitFlowLabelInteraction {
  hovered?: ReadonlySet<number> | readonly number[];
  selected?: ReadonlySet<number> | readonly number[];
  searched?: ReadonlySet<number> | readonly number[];
}

/** Previous-frame state feeding both hysteresis mechanisms. */
export interface GitFlowLabelPreviousState {
  tier?: GitFlowLabelTier;
  /** nodeIndex set placed last frame (collision-margin hysteresis, P1.2). */
  placed?: ReadonlySet<number> | readonly number[];
}

export type GitFlowLabelAnchor = "fork" | "tip" | "stagger";

export interface PlacedGitFlowLabel {
  nodeIndex: number;
  /** Display text — the compacted form, or the FULL name on interaction. */
  text: string;
  /** True when `text` is the full, uncompacted branch name (I3). */
  fullName: boolean;
  cls: GitFlowLabelClass;
  /** Which anchor accepted the pill (P2.2 fallback chain). */
  anchor: GitFlowLabelAnchor;
  /** Pill CENTRE in WORLD coordinates (place the box node here). */
  x: number;
  y: number;
  /** Pill centre + extents in DEVICE px (the accepted AABB is centre ± w/2, h/2). */
  screenX: number;
  screenY: number;
  w: number;
  h: number;
}

export interface GitFlowLabelPlacement {
  tier: GitFlowLabelTier;
  /** Accepted labels, in acceptance (priority) order. */
  labels: PlacedGitFlowLabel[];
  /** Accepted nodeIndex set — feed back as `previous.placed` next frame. */
  placed: Set<number>;
  /** Candidates the tier admitted but culling rejected (diagnostics/tests). */
  culled: number[];
}

export interface GitFlowLabelPolicyInput {
  /** Anchor hints from {@link computeGitFlowPositions} (`layout.branchLabels`). */
  labels: readonly GitFlowBranchLabel[];
  /** The SAME measureText service the box draw path uses (or a deterministic
   * approximation — see {@link approximateLabelMeasure} for headless builds). */
  measure: (text: string, font: string) => number;
  camera: GitFlowLabelCamera;
  interaction?: GitFlowLabelInteraction;
  previous?: GitFlowLabelPreviousState;
}

function toSet(v: ReadonlySet<number> | readonly number[] | undefined): ReadonlySet<number> {
  if (!v) return EMPTY_SET;
  return v instanceof Set ? v : new Set(v);
}
const EMPTY_SET: ReadonlySet<number> = new Set();

/**
 * Resolved pill BASE HEIGHT in CSS px for a policy option set. THE sync point
 * between the policy's measured AABBs and the renderer's drawn pills: pass
 * this value as `GraphRendererOptions.boxBaseHeightPx` on the git-flow view.
 */
export function gitFlowLabelBoxHeightPx(options: GitFlowLabelPolicyOptions = {}): number {
  return (
    options.boxHeightPx ??
    BOX_BASE_HEIGHT_PX * (options.labelScale ?? DEFAULT_GITFLOW_LABEL_SCALE)
  );
}

/**
 * Deterministic APPROXIMATE text measurer for headless/fixture builds (no
 * canvas): a per-glyph width table that deliberately OVER-estimates average
 * sans-serif widths, so policy AABBs stay conservative vs the real
 * measureText the renderer hugs. Browser callers should pass a real
 * `ctx.measureText` instead.
 */
export function approximateLabelMeasure(text: string, font: string): number {
  const fontPx = Number.parseFloat(font) || 10;
  let units = 0;
  for (const ch of text) {
    if ("iljI.,:;!|'`·".includes(ch)) units += 0.38;
    else if ("mwMW@#%".includes(ch)) units += 0.95;
    else if (ch >= "A" && ch <= "Z") units += 0.78;
    else units += 0.62;
  }
  return units * fontPx;
}

interface Aabb {
  x0: number;
  y0: number;
  x1: number;
  y1: number;
}

/** Uniform occupancy grid over accepted AABBs (P1.2 grid occupancy). */
class OccupancyGrid {
  private readonly cell: number;
  private readonly cells = new Map<string, number[]>();
  private readonly boxes: Aabb[] = [];

  constructor(cell = 64) {
    this.cell = cell;
  }

  collides(box: Aabb): boolean {
    const cx0 = Math.floor(box.x0 / this.cell);
    const cx1 = Math.floor(box.x1 / this.cell);
    const cy0 = Math.floor(box.y0 / this.cell);
    const cy1 = Math.floor(box.y1 / this.cell);
    const seen = new Set<number>();
    for (let cy = cy0; cy <= cy1; cy += 1) {
      for (let cx = cx0; cx <= cx1; cx += 1) {
        const bucket = this.cells.get(`${cx},${cy}`);
        if (!bucket) continue;
        for (const i of bucket) {
          if (seen.has(i)) continue;
          seen.add(i);
          const b = this.boxes[i]!;
          if (box.x0 < b.x1 && box.x1 > b.x0 && box.y0 < b.y1 && box.y1 > b.y0) return true;
        }
      }
    }
    return false;
  }

  insert(box: Aabb): void {
    const index = this.boxes.length;
    this.boxes.push(box);
    const cx0 = Math.floor(box.x0 / this.cell);
    const cx1 = Math.floor(box.x1 / this.cell);
    const cy0 = Math.floor(box.y0 / this.cell);
    const cy1 = Math.floor(box.y1 / this.cell);
    for (let cy = cy0; cy <= cy1; cy += 1) {
      for (let cx = cx0; cx <= cx1; cx += 1) {
        const key = `${cx},${cy}`;
        const bucket = this.cells.get(key);
        if (bucket) bucket.push(index);
        else this.cells.set(key, [index]);
      }
    }
  }
}

/**
 * THE label policy (compaction → tier gate → priority → anchored placement).
 *
 * Placement runs in DESCENDING priority order (P1.2): interaction → trunk →
 * release/hotfix → human features (newer tip first) → tip-only refs →
 * autogenerated (T2 only). Each candidate tries the bounded anchor chain
 * (P2.2) fork-left → tip-right → ONE stagger slot; the first anchor whose
 * AABB does not overlap any accepted pill wins; otherwise the label is
 * CULLED (I1 — never drawn overlapping). New labels (absent from
 * `previous.placed`) additionally need `hysteresisMarginPx` clearance, so
 * pan/zoom does not flicker labels sitting on the knife edge.
 */
export function placeGitFlowLabels(
  input: GitFlowLabelPolicyInput,
  options: GitFlowLabelPolicyOptions = {},
): GitFlowLabelPlacement {
  const { labels, measure, camera } = input;
  const pixelRatio = camera.pixelRatio ?? 1;
  const zoom = camera.zoom;
  const margin = options.hysteresisMarginPx ?? DEFAULT_HYSTERESIS_MARGIN_PX;
  const boxHeightPx = gitFlowLabelBoxHeightPx(options);
  const tipClearancePx = options.tipClearancePx ?? DEFAULT_TIP_CLEARANCE_PX;
  const staggerGapPx = options.staggerGapPx ?? DEFAULT_STAGGER_GAP_PX;

  const tier = resolveGitFlowLabelTier(zoom, input.previous?.tier, options);
  const hovered = toSet(input.interaction?.hovered);
  const selected = toSet(input.interaction?.selected);
  const searched = toSet(input.interaction?.searched);
  const previousPlaced = toSet(input.previous?.placed);

  const compacted = compactGitFlowLabels(labels, options);
  const compactedByIndex = new Map<number, CompactedGitFlowLabel>();
  for (const c of compacted) compactedByIndex.set(c.nodeIndex, c);

  interface Candidate {
    label: GitFlowBranchLabel;
    comp: CompactedGitFlowLabel;
    cls: GitFlowLabelClass;
    rank: number;
    recency: number; // tip x — newer (larger) first within `feature`
    hash: number;
  }

  const isInteraction = (i: number): boolean =>
    hovered.has(i) || selected.has(i) || searched.has(i);

  const candidates: Candidate[] = [];
  const trunkSeen = new Set<string>(); // one trunk label per repo band
  for (const label of labels) {
    const comp = compactedByIndex.get(label.nodeIndex)!;
    let cls: GitFlowLabelClass;
    if (isInteraction(label.nodeIndex)) cls = "interaction";
    else if (comp.autogenerated) cls = "autogenerated";
    else if (label.lane === 0 && !trunkSeen.has(label.repo)) {
      cls = "trunk";
      trunkSeen.add(label.repo);
    } else if (/^(release|hotfix)\//.test(comp.fullName) || /^(rel|hotfix):/.test(comp.text)) {
      cls = "release";
    } else if (label.entry === "tip-only") cls = "tip-ref";
    else cls = "feature";

    // P2.1 tier gate: T0 = trunk + interaction; T1 adds every HUMAN class;
    // T2 adds the autogenerated (demoted) class, still culling-gated.
    if (tier === 0 && cls !== "interaction" && cls !== "trunk") continue;
    if (tier <= 1 && cls === "autogenerated") continue;

    candidates.push({
      label,
      comp,
      cls,
      rank: CLASS_RANK[cls],
      recency: cls === "feature" ? (label.tipX ?? label.x) : 0,
      hash: gitFlowNameHash(comp.fullName),
    });
  }

  // P1.2 determinism: stable sort key (priority, recency, then name hash).
  candidates.sort((a, b) => {
    if (a.rank !== b.rank) return a.rank - b.rank;
    if (a.recency !== b.recency) return b.recency - a.recency;
    if (a.hash !== b.hash) return a.hash - b.hash;
    if (a.comp.fullName !== b.comp.fullName) return a.comp.fullName < b.comp.fullName ? -1 : 1;
    return a.label.nodeIndex - b.label.nodeIndex;
  });

  const sx = (wx: number): number => (wx - camera.x) * zoom + camera.width / 2;
  const sy = (wy: number): number => (wy - camera.y) * zoom + camera.height / 2;
  const wx = (px: number): number => camera.x + (px - camera.width / 2) / zoom;
  const wy = (py: number): number => camera.y + (py - camera.height / 2) / zoom;

  const grid = new OccupancyGrid();
  const placedLabels: PlacedGitFlowLabel[] = [];
  const placedSet = new Set<number>();
  const culled: number[] = [];

  const boxHeight = boxHeightPx * pixelRatio * zoom;

  for (const cand of candidates) {
    const full = cand.cls === "interaction";
    const text = full ? cand.comp.fullName : cand.comp.text;
    // Measured pill dims — the SAME boxDimensions the draw path uses, so the
    // accepted AABB is exactly the pill the renderer will draw (incl. the
    // max-width pixel-fit cap).
    const dims = boxDimensions(boxHeight, text, measure);
    const halfW = dims.w / 2;
    const halfH = dims.h / 2;
    const m = previousPlaced.has(cand.label.nodeIndex) ? 0 : margin;

    // P2.2 bounded anchor chain: fork-left → tip-right → ONE stagger slot.
    const anchors: Array<{ anchor: GitFlowLabelAnchor; cx: number; cy: number }> = [];
    const forkX = sx(cand.label.x);
    const forkY = sy(cand.label.y);
    anchors.push({ anchor: "fork", cx: forkX, cy: forkY });
    if (cand.label.tipX !== undefined && cand.label.tipX !== cand.label.x) {
      const clear = tipClearancePx * pixelRatio * zoom + 4;
      anchors.push({ anchor: "tip", cx: sx(cand.label.tipX) + clear + halfW, cy: forkY });
    }
    anchors.push({ anchor: "stagger", cx: forkX, cy: forkY - (dims.h + staggerGapPx) });

    let accepted = false;
    for (const a of anchors) {
      const test: Aabb = {
        x0: a.cx - halfW - m,
        y0: a.cy - halfH - m,
        x1: a.cx + halfW + m,
        y1: a.cy + halfH + m,
      };
      if (grid.collides(test)) continue;
      grid.insert({ x0: a.cx - halfW, y0: a.cy - halfH, x1: a.cx + halfW, y1: a.cy + halfH });
      placedLabels.push({
        nodeIndex: cand.label.nodeIndex,
        text,
        fullName: full,
        cls: cand.cls,
        anchor: a.anchor,
        x: wx(a.cx),
        y: wy(a.cy),
        screenX: a.cx,
        screenY: a.cy,
        w: dims.w,
        h: dims.h,
      });
      placedSet.add(cand.label.nodeIndex);
      accepted = true;
      break;
    }
    if (!accepted) culled.push(cand.label.nodeIndex);
  }

  return { tier, labels: placedLabels, placed: placedSet, culled };
}
